version: '3'
services:
  app:
    image: 'oo9699/intro-me-server:latest'
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=introme
      - DB_NAME=introme
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./resources/grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: introme
      MYSQL_DATABASE: introme
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    volumes:
      - ./resources/data:/var/lib/mysql
      - ./resources/db/migrate:/docker-entrypoint-initdb.d
      - ./resources/conf.d:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
