version: '3'
services:
  app:
    image: 'hyebinnn/introme-server-final9:latest'
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/introme?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: introme
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3030:3030"
    volumes:
      - ./resources/grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: introme
      MYSQL_DATABASE: introme
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    volumes:
      - ./resources/data:/var/lib/mysql
      - ./resources/db/migrate:/docker-entrypoint-initdb.d
      - ./resources/conf.d:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
