version: '3'
services:
  db:
    image: mysql:8.0 # or whatever version you prefer
    environment:
      MYSQL_ROOT_PASSWORD: introme
      MYSQL_DATABASE: introme
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./db/migrate:/docker-entrypoint-initdb.d
    command: "|
      sleep 5
      mysql -u root -pintrome introme < docker-entrypoint-initdb.d/migrate.sql
      "