DROP TABLE IF EXISTS company;
DROP TABLE if exists talent;

create table company (
                         id bigint generated by default as identity,
                         company_info varchar(255),
                         identity_color varchar(255) not null,
                         image varchar(255) not null,
                         name varchar(255) not null,
                         permission varchar(255) not null check (permission in ('APPROVED','PENDING','DENIED')),
                         updated_at timestamp(6),
                         primary key (id)
);

create table talent (
                        id bigint generated by default as identity,
                        base_url varchar(255),
                        description varchar(255),
                        icon varchar(255),
                        keyword varchar(255) not null,
                        permission varchar(255) check (permission in ('APPROVED','PENDING','DENIED')),
                        company_id bigint,
                        primary key (id)
);



INSERT INTO COMPANY (COMPANY_INFO, IDENTITY_COLOR, IMAGE, NAME, PERMISSION, updated_at) VALUES
                                                                                ('{"location":"서울특별시 강서구","url":"www.naver.com","recruitUrl":"www.recruit.com","techBlog":"www.tech.com"}', '#YELDSM', '.icon', '카카오', 'APPROVED', now()),
                                                                                ('{"location":"서울특별시 강남구","url":"www.naver.com","recruitUrl":"www.recruit.com","techBlog":"www.tech.com"}', '#CSMSMD', '.icon', '신한은행', 'APPROVED', now()),
                                                                                ('{"location":"서울특별시 강남구","url":"www.naver.com","recruitUrl":"www.recruit.com","techBlog":"www.tech.com"}', '#EEEEEE', '.icon', '네이버', 'APPROVED', now()),
                                                                                ('{"location":"서울특별시 강서구","url":"www.naver.com","recruitUrl":"www.recruit.com","techBlog":"www.tech.com"}', '#YELDSM', '.icon', '우아한형제들', 'APPROVED', now()),
                                                                                ('{"location":"서울특별시 강남구","url":"www.naver.com","recruitUrl":"www.recruit.com","techBlog":"www.tech.com"}', '#CSMSMD', '.icon', '쿠팡', 'APPROVED', now()),
                                                                                ('{"location":"서울특별시 강남구","url":"www.naver.com","recruitUrl":"www.recruit.com","techBlog":"www.tech.com"}', '#EEEEEE', '.icon', '라인', 'APPROVED', now()),
                                                                                ('{"location":"서울특별시 강서구","url":"www.naver.com","recruitUrl":"www.recruit.com","techBlog":"www.tech.com"}', '#YELDSM', '.icon', '당근', 'APPROVED', now()),
                                                                                ('{"location":"서울특별시 강남구","url":"www.naver.com","recruitUrl":"www.recruit.com","techBlog":"www.tech.com"}', '#CSMSMD', '.icon', '토스', 'APPROVED', now()),
                                                                                ('{"location":"서울특별시 강남구","url":"www.naver.com","recruitUrl":"www.recruit.com","techBlog":"www.tech.com"}', '#EEEEEE', '.icon', '야후꾸러기', 'APPROVED', now()),
                                                                                ('{"location":"서울특별시 강서구","url":"www.naver.com","recruitUrl":"www.recruit.com","techBlog":"www.tech.com"}', '#YELDSM', '.icon', '에이블리', 'APPROVED', now()),
                                                                                ('{"location":"서울특별시 강남구","url":"www.naver.com","recruitUrl":"www.recruit.com","techBlog":"www.tech.com"}', '#CSMSMD', '.icon', '인프런', 'APPROVED', now()),
                                                                                ('{"location":"서울특별시 강남구","url":"www.naver.com","recruitUrl":"www.recruit.com","techBlog":"www.tech.com"}', '#EEEEEE', '.icon', '깃허브', 'APPROVED', now()),
                                                                                ('{"location":"서울특별시 강서구","url":"www.naver.com","recruitUrl":"www.recruit.com","techBlog":"www.tech.com"}', '#YELDSM', '.icon', '링크드인', 'APPROVED', now());


INSERT INTO TALENT (BASE_URL, DESCRIPTION, ICON, KEYWORD, PERMISSION, COMPANY_ID) VALUES
                                                                                      ('', '고객이 원하는 최고의 경험을 만든다.', 'icon.png', '고객중심', 'APPROVED', 1),
                                                                                      ('', '자율과 책임에 기반하여 성과를 낸다.', 'icon.png', '주도적 몰입', 'APPROVED', 2),
                                                                                      ('', '현재에 만족하지 않고 도전한다.', 'icon.png', '대담한 도전', 'APPROVED', 2),
                                                                                      ('', '현재에 만족하지 않고 도전한다.', 'icon.png', '대담한 도전', 'APPROVED', 3),
                                                                                      ('', '현재에 만족하지 않고 도전한다.', 'icon.png', '현재에 만족하지않는 정신', 'PENDING', 3),
                                                                                      ('', '고객이 원하는 최고의 경험을 만든다.', 'icon.png', '고객중심', 'APPROVED', 3),
                                                                                      ('', '자율과 책임에 기반하여 성과를 낸다.', 'icon.png', '주도적 몰입', 'APPROVED', 4),
                                                                                      ('', '현재에 만족하지 않고 도전한다.', 'icon.png', '대담한 도전', 'APPROVED', 5),
                                                                                      ('', '현재에 만족하지 않고 도전한다.', 'icon.png', '대담한 도전', 'APPROVED', 6),
                                                                                      ('', '현재에 만족하지 않고 도전한다.', 'icon.png', '현재에 만족하지않는 정신', 'PENDING', 6),
                                                                                      ('', '고객이 원하는 최고의 경험을 만든다.', 'icon.png', '고객중심', 'APPROVED', 7),
                                                                                      ('', '자율과 책임에 기반하여 성과를 낸다.', 'icon.png', '주도적 몰입', 'APPROVED', 8),
                                                                                      ('', '현재에 만족하지 않고 도전한다.', 'icon.png', '대담한 도전', 'APPROVED', 9),
                                                                                      ('', '현재에 만족하지 않고 도전한다.', 'icon.png', '대담한 도전', 'APPROVED', 10),
                                                                                      ('', '현재에 만족하지 않고 도전한다.', 'icon.png', '현재에 만족하지않는 정신', 'APPROVED', 11),
                                                                                      ('', '고객이 원하는 최고의 경험을 만든다.', 'icon.png', '고객중심', 'APPROVED', 12),
                                                                                      ('', '자율과 책임에 기반하여 성과를 낸다.', 'icon.png', '주도적 몰입', 'APPROVED', 13),
                                                                                      ('', '현재에 만족하지 않고 도전한다.', 'icon.png', '대담한 도전', 'APPROVED', 13);